name: Verify Go Module

# don't limit to main branch
# consider maintenance branch
on:
  pull_request:
    branches:
      - 'release-branch.**'
      - main
    paths-ignore:
      - '.github/**'
      - LICENSE
      - README.md
      - '.gitignore'

jobs:
  llpkg-verification:
    name: Verify Go Module
    strategy:
      matrix:
        os:
          - macos-13
          - macos-latest
          - ubuntu-24.04
          - ubuntu-24.04-arm
        llvm: [19]
        llgo: [e68355d94f9f9ec17caae6e0d397bd55f8c5ec33]
        llcppg: [v0.7.3]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check out LLGo
        uses: actions/checkout@v4
        with:
          repository: 'goplus/llgo'
          path: .llgo
          ref: ${{matrix.llgo}}
      - name: Check out LLCppg
        uses: actions/checkout@v4
        with:
          repository: 'goplus/llcppg'
          path: .llcppg
          ref: ${{matrix.llcppg}}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
      - name: Set up Tool
        run: |
          go install -v github.com/PengPengPeng717/llpkgstore/cmd/llpkgstore@latest
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install llvm@${{matrix.llvm}} bdw-gc openssl libffi libuv cmake conan lld@${{matrix.llvm}}
          brew link --force libffi
          echo "$(brew --prefix llvm@${{matrix.llvm}})/bin" >> $GITHUB_PATH
          echo "$(brew --prefix lld@${{matrix.llvm}})/bin" >> $GITHUB_PATH
      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${{matrix.llvm}} main" | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get install -y llvm-${{matrix.llvm}}-dev \
            clang-${{matrix.llvm}} \
            libclang-${{matrix.llvm}}-dev \
            lld-${{matrix.llvm}} \
            libunwind-${{matrix.llvm}}-dev \
            libc++-${{matrix.llvm}}-dev \
            pkg-config libgc-dev libssl-dev zlib1g-dev libffi-dev libuv1-dev
          echo "/usr/lib/llvm-${{matrix.llvm}}/bin" >> $GITHUB_PATH
      - name: Pre setup Python and Conan
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install conan pydump
          go install github.com/goplus/hdq/chore/pysigfetch@v0.8.1
      - name: Pre setup Python and Conan
        if: startsWith(matrix.os, 'macos')
        run: |
          python3 -m pip install conan pydump --break-system-packages
          go install github.com/goplus/hdq/chore/pysigfetch@v0.8.1
      - name: Set up Conan
        run: |
          conan profile detect
      - name: Setup LLGo
        working-directory: .llgo
        run: |
          go install -v ./cmd/llgo/...
          export LLGO_ROOT=$(pwd)
          echo "LLGO_ROOT=$LLGO_ROOT" >> $GITHUB_ENV
          # https://github.com/goplus/llgo/issues/1135
          echo "LLGO_RPATH_CHANGE=ON" >> $GITHUB_ENV
      - name: Setup LLCppg (for C/C++ packages)
        working-directory: .llcppg
        run: |
          llgo install ./_xtool/llcppsymg
          llgo install ./_xtool/llcppsigfetch
          go install github.com/goplus/llcppg/cmd/llcppcfg@${{matrix.llcppg}}
          go install github.com/goplus/llcppg/cmd/gogensig@${{matrix.llcppg}}
          go install github.com/goplus/llcppg/cmd/llcppg@${{matrix.llcppg}}
      - name: Setup LLPyg (for Python packages)
        working-directory: .llgo
        run: |
          go install -v ./chore/...
      - name: Set up Python environment
        run: |
          echo "PYTHONPATH=/usr/local/lib/python3.12/site-packages:/usr/lib/python3.12/site-packages" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=go1.24.5" >> $GITHUB_ENV
      - name: Install Python dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          python3 -m pip install numpy==1.26.4
      - name: Install Python dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          python3 -m pip install numpy==1.26.4 --break-system-packages
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: Verification & Prebuilt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: llpkgstore verification
      - name: Run demotest process
        env:
          LLPKG_PATH: ${{ env.LLPKG_PATH }}
        run: llpkgstore demotest
